server:
  port: 8181
spring:
  profiles:
    active: dev
  application:
    name: DataToKafkaService
  cloud:
    config:
      username: user
      password: "{cipher}2affbafff8dd5d6006af3ffddc87eca5bdfbc04c7cf7e5c5845c3ec8cecd3b25"
      name: DataToKafkaService
      uri: http://127.0.0.1:8888
  config:
    name: DataToKafkaService
    import: optional:configserver:http://127.0.0.1:8888
logging:
  level:
    org.springframework.cloud.config: debug