spring:
  application:
    name: data-stream-to-kafka-service
  profiles:
    active: data-stream-to-kafka-service
  config:
    import: optional:configserver:http://localhost:8888
    name: config-client,data-stream-to-kafka-service