data-stream-to-kafka-service:
  data-stream-filter-keywords:
    - Java
    - Spring
    - Microservices
    - Kafka
    - Elasticsearch
  domain-filter:
    #    - en.wikipedia.org
    - vi.wikipedia.org

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 100000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: wikimedia-recent-changes
  topic-names-to-create:
    - wikimedia-recent-changes
  number-partitions: 3
  replication-factor: 3

logging:
  level:
    root: info
  file:
    name: logs/twitter-to-kafka-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
