version: '3.7'
services:
  wikimedia-to-kafka-service:
    image: ${GROUP_ID}/wikimedia.to.kafka.service:${SERVICE_VERSION:-latest}
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_EVENT_MICROSERVICES=DEBUG"
      - "LOGGING_LEVEL_ROOT=INFO"
      - "KAFKA_CONFIG_BOOTSTRAP_SERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092"
      - "KAFKA_CONFIG_SCHEMA_REGISTRY_URL=http://schema-registry:8081"
    networks:
      - ${GLOBAL_NETWORK:-kafka}