/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.event.driven.microservices.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RCLengthArvoModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2775242499010402776L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RCLengthArvoModel\",\"namespace\":\"com.event.driven.microservices.kafka.avro.model\",\"fields\":[{\"name\":\"old\",\"type\":[\"null\",\"long\"]},{\"name\":\"new\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RCLengthArvoModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RCLengthArvoModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RCLengthArvoModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RCLengthArvoModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RCLengthArvoModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RCLengthArvoModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RCLengthArvoModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RCLengthArvoModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RCLengthArvoModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Long old;
  private long new$;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RCLengthArvoModel() {}

  /**
   * All-args constructor.
   * @param old The new value for old
   * @param new$ The new value for new
   */
  public RCLengthArvoModel(java.lang.Long old, java.lang.Long new$) {
    this.old = old;
    this.new$ = new$;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return old;
    case 1: return new$;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: old = (java.lang.Long)value$; break;
    case 1: new$ = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'old' field.
   * @return The value of the 'old' field.
   */
  public java.lang.Long getOld() {
    return old;
  }


  /**
   * Sets the value of the 'old' field.
   * @param value the value to set.
   */
  public void setOld(java.lang.Long value) {
    this.old = value;
  }

  /**
   * Gets the value of the 'new$' field.
   * @return The value of the 'new$' field.
   */
  public long getNew$() {
    return new$;
  }


  /**
   * Sets the value of the 'new$' field.
   * @param value the value to set.
   */
  public void setNew$(long value) {
    this.new$ = value;
  }

  /**
   * Creates a new RCLengthArvoModel RecordBuilder.
   * @return A new RCLengthArvoModel RecordBuilder
   */
  public static com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder newBuilder() {
    return new com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder();
  }

  /**
   * Creates a new RCLengthArvoModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RCLengthArvoModel RecordBuilder
   */
  public static com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder newBuilder(com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder other) {
    if (other == null) {
      return new com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder();
    } else {
      return new com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder(other);
    }
  }

  /**
   * Creates a new RCLengthArvoModel RecordBuilder by copying an existing RCLengthArvoModel instance.
   * @param other The existing instance to copy.
   * @return A new RCLengthArvoModel RecordBuilder
   */
  public static com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder newBuilder(com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel other) {
    if (other == null) {
      return new com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder();
    } else {
      return new com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for RCLengthArvoModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RCLengthArvoModel>
    implements org.apache.avro.data.RecordBuilder<RCLengthArvoModel> {

    private java.lang.Long old;
    private long new$;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.old)) {
        this.old = data().deepCopy(fields()[0].schema(), other.old);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.new$)) {
        this.new$ = data().deepCopy(fields()[1].schema(), other.new$);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RCLengthArvoModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.old)) {
        this.old = data().deepCopy(fields()[0].schema(), other.old);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.new$)) {
        this.new$ = data().deepCopy(fields()[1].schema(), other.new$);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'old' field.
      * @return The value.
      */
    public java.lang.Long getOld() {
      return old;
    }


    /**
      * Sets the value of the 'old' field.
      * @param value The value of 'old'.
      * @return This builder.
      */
    public com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder setOld(java.lang.Long value) {
      validate(fields()[0], value);
      this.old = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'old' field has been set.
      * @return True if the 'old' field has been set, false otherwise.
      */
    public boolean hasOld() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'old' field.
      * @return This builder.
      */
    public com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder clearOld() {
      old = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'new$' field.
      * @return The value.
      */
    public long getNew$() {
      return new$;
    }


    /**
      * Sets the value of the 'new$' field.
      * @param value The value of 'new$'.
      * @return This builder.
      */
    public com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder setNew$(long value) {
      validate(fields()[1], value);
      this.new$ = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'new$' field has been set.
      * @return True if the 'new$' field has been set, false otherwise.
      */
    public boolean hasNew$() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'new$' field.
      * @return This builder.
      */
    public com.event.driven.microservices.kafka.avro.model.RCLengthArvoModel.Builder clearNew$() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RCLengthArvoModel build() {
      try {
        RCLengthArvoModel record = new RCLengthArvoModel();
        record.old = fieldSetFlags()[0] ? this.old : (java.lang.Long) defaultValue(fields()[0]);
        record.new$ = fieldSetFlags()[1] ? this.new$ : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RCLengthArvoModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<RCLengthArvoModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RCLengthArvoModel>
    READER$ = (org.apache.avro.io.DatumReader<RCLengthArvoModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.old == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.old);
    }

    out.writeLong(this.new$);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.old = null;
      } else {
        this.old = in.readLong();
      }

      this.new$ = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.old = null;
          } else {
            this.old = in.readLong();
          }
          break;

        case 1:
          this.new$ = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










