twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Spring
    - Microservices
    - Kafka
    - Elasticsearch

logging:
  level:
    root: info
  file:
    name: logs/twitter-to-kafka-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
spring:
  activemq:
    broker-url: tcp://publicdatafeeds.networkrail.co.uk:61618
    user: vanphuoc3012@gmail.com
    password: Qy4eAWsNwR24!na
